const versiculos = [
  {
    id: 1,
    texto: `Depois diga ao faraó que assim diz o Senhor: "Israel é o meu primeiro filho,"`,
    livro: "Êxodo",
    capitulo: 4,
    versiculo: 22,
  },
  {
    id: 2,
    texto: `Josué disse a todo o povo: "Assim diz o Senhor, o Deus de Israel: 'Há muito, os seus antepassados, inclusive Terá, pai de Abraão e de Naor, viviam além do Eufrates e adoravam outros deuses.'"`,
    livro: "Josué",
    capitulo: 24,
    versiculo: 2,
  },
  {
    id: 3,
    texto: `e disse a eles: "Assim diz o Senhor, o Deus de Israel: 'Eu tirei Israel do Egito e libertei vocês do poder do Egito e de todos os reinos que os oprimiam.'`,
    livro: "1ªSamuel",
    capitulo: 10,
    versiculo: 18,
  },
  {
    id: 4,
    texto: `Por isso o Soberano, o Senhor dos Exércitos, diz: "Povo meu que vive em Sião, não tenha medo dos assírios quando eles o espancam com uma vara e erguem contra você um bastão como fez o Egito."`,
    livro: "Isaías",
    capitulo: 10,
    versiculo: 24,
  },
  {
    id: 5,
    texto: `Levantarei do meio dos seus irmãos um profeta como você; porei minhas palavras na sua boca, e ele dirá a vocês tudo o que eu lhe ordenar. 19- Se alguém não ouvir as minhas palavras, que o profeta falará em meu nome, eu mesmo lhe pedirei contas. 20- Mas o profeta que ousar falar em meu nome alguma coisa que eu não lhe ordenei, ou o que falar em nome de outros deuses, terá que ser morto.`,
    livro: "Deuteronômio",
    capitulo: 18,
    versiculo: 18,
  },
  {
    id: 6,
    texto: `Porque o Senhor, o seu Deus, é o Deus dos deuses e o Senhor dos senhores, o grande Deus, poderoso e temível, que não age com parcialidade nem aceita suborno.`,
    livro: "Jeremias",
    capitulo: 1,
    versiculo: 9,
  },
  {
    id: 7,
    texto: `Toda a Escritura é inspirada por Deus e útil para o ensino, para a repreensão, para a correção e para a instrução em justiça,`,
    livro: "2ªTimóteo",
    capitulo: 3,
    versiculo: 16,
  },
  {
    id: 8,
    texto: `Ele escreve da mesma forma em todas as suas cartas, falando nelas destes assuntos. Suas cartas contêm algumas coisas difíceis de entender, as quais os ignorantes e instáveis torcem, como também o fazem com as demais Escrituras, para a própria destruição deles.`,
    livro: "2ªPedro",
    capitulo: 3,
    versiculo: 16,
  },
  {
    id: 9,
    texto: `pois a Escritura diz: "Não amordacem o boi enquanto está debulhando o cereal" e "o trabalhador merece o seu salário".`,
    livro: "1ªTimóteo",
    capitulo: 5,
    versiculo: 18,
  },
  {
    id: 10,
    texto: `"Não amordacem o boi enquanto está debulhando o cereal"`,
    livro: "Deuteronômio",
    capitulo: 25,
    versiculo: 4,
  },
  {
    id: 11,
    texto: `Fiquem naquela casa e comam e bebam o que derem a vocês, pois o trabalhador merece o seu salário. Não fiquem mudando de casa em casa.`,
    livro: "Lucas",
    capitulo: 10,
    versiculo: 7,
  },
  {
    id: 12,
    texto: `Se alguém pensa que é profeta ou espiritual, reconheça que o que estou escrevendo a vocês é mandamento do Senhor`,
    livro: "1ªCoríntios",
    capitulo: 14,
    versiculo: 37,
  },
  {
    id: 13,
    texto: `Mas o Conselheiro, o Espírito Santo, que o Pai enviará em meu nome, ensinará a vocês todas as coisas e fará vocês lembrarem tudo o que eu disse.`,
    livro: "João",
    capitulo: 14,
    versiculo: 26,
  },
  {
    id: 14,
    texto: `Há muito tempo Deus falou muitas vezes e de várias maneiras aos nossos antepassados por meio dos profetas,`,
    livro: "Hebreus",
    capitulo: 1,
    versiculo: 1,
  },
  {
    id: 15,
    texto: `Ao anjo da igreja em Éfeso escreva: "Estas são as palavras daquele que tem as sete estrelas em sua mão direita e anda entre os sete candelabros de ouro." 8- Ao anjo da igreja em Esmirna escreva: "Estas são as palavras daquele que é o Primeiro e o Último, que morreu e tornou a viver." 12- Ao anjo da igreja em Pérgamo escreva: "Estas são as palavras daquele que tem a espada afiada de dois gumes."`,
    livro: "Apocalipse",
    capitulo: 2,
    versiculo: 1,
  },
  {
    id: 16,
    texto: `Muitos já se dedicaram a elaborar um relato dos fatos que se cumpriram entre nós, 2- conforme nos foram transmitidos por aqueles que desde o início foram testemunhas oculares e servos da palavra. 3- Eu mesmo investiguei tudo cuidadosamente, desde o começo, e decidi escrever-te um relato ordenado, ó excelentíssimo Teófilo,`,
    livro: "Lucas",
    capitulo: 1,
    versiculo: 1,
  },
  {
    id: 17,
    texto: `As minhas ovelhas ouvem a minha voz; eu as conheço, e elas me seguem.`,
    livro: "João",
    capitulo: 10,
    versiculo: 27,
  },
  {
    id: 18,
    texto: `Santifica-os na verdade; a tua palavra é a verdade.`,
    livro: "João",
    capitulo: 17,
    versiculo: 17,
  },
];

export default versiculos;
